apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: motd-service
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_TAG}}"
  artifacts:
    - image: ghcr.io/tobias-neubert/motd-service
      jib: {}
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - kustomize/dev
  - name: staging
    manifests:
      kustomize:
        paths:
          - kustomize/staging
  - name: prod
    manifests:
      kustomize:
        paths:
          - kustomize/prod
