apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hello-service
build:
  artifacts:
  - image: neubert/hello-service
    jib:
      project: hello-service
manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/istio.yaml
